from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    """
    класс описывающий внешний вид и структурные элементы графического интерфейса
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(797, 570))
        MainWindow.setMaximumSize(QtCore.QSize(797, 570))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.imagePreView = QtWidgets.QGraphicsView(self.centralwidget)
        self.imagePreView.setGeometry(QtCore.QRect(0, 0, 481, 351))
        self.imagePreView.setObjectName("imagePreView")
        self.LogBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.LogBrowser.setGeometry(QtCore.QRect(0, 360, 801, 211))
        self.LogBrowser.setObjectName("LogBrowser")
        self.tariningPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.tariningPushButton.setGeometry(QtCore.QRect(490, 0, 301, 41))
        self.tariningPushButton.setObjectName("tariningPushButton")
        self.liteTrainingPushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.liteTrainingPushButton_2.setGeometry(QtCore.QRect(490, 40, 301, 41))
        self.liteTrainingPushButton_2.setObjectName("liteTrainingPushButton_2")
        self.predictionButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.predictionButton_3.setGeometry(QtCore.QRect(490, 310, 301, 41))
        self.predictionButton_3.setObjectName("predictionButton_3")
        self.imagePathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.imagePathLineEdit.setGeometry(QtCore.QRect(490, 150, 301, 31))
        self.imagePathLineEdit.setReadOnly(True)
        self.imagePathLineEdit.setObjectName("imagePathLineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 130, 171, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 210, 111, 30))
        self.label_2.setObjectName("label_2")
        self.modelPathLineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.modelPathLineEdit_2.setGeometry(QtCore.QRect(490, 240, 301, 31))
        self.modelPathLineEdit_2.setReadOnly(True)
        self.modelPathLineEdit_2.setObjectName("modelPathLineEdit_2")
        self.pathImageButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pathImageButton_4.setGeometry(QtCore.QRect(490, 180, 301, 31))
        self.pathImageButton_4.setObjectName("pathImageButton_4")
        self.pathModelButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pathModelButton_5.setGeometry(QtCore.QRect(490, 270, 301, 31))
        self.pathModelButton_5.setObjectName("pathModelButton_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(490, 80, 181, 21))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Описание изображений"))
        self.tariningPushButton.setText(_translate("MainWindow", "Тренировка (необходимо 32 ГБ RAM)"))
        self.liteTrainingPushButton_2.setText(_translate("MainWindow", "Облегчённый режим тренировки"))
        self.predictionButton_3.setText(_translate("MainWindow", "Выполнить описание"))
        self.label.setText(_translate("MainWindow", "Путь к изображению:"))
        self.label_2.setText(_translate("MainWindow", "Путь к модели:"))
        self.pathImageButton_4.setText(_translate("MainWindow", "Указать путь к изображению"))
        self.pathModelButton_5.setText(_translate("MainWindow", "Указать путь к модели"))
        self.checkBox.setText(_translate("MainWindow", "Полная тренировка"))

